### ISSUE TITLE
Error about 'data' of 'object null' as it is null

### ISSUE THREAD

**Issue by jmarrr** [blockworks-foundation/liquidator-v3#24]
At some point I am getting this error
```
Error checking accounts: TypeError: Cannot destructure property 'data' of 'object null' as it is null.
    at C:\Users\Administrator\Desktop\liquidator-v3\node_modules\@blockworks-foundation\mango-client\src\utils\utils.ts:463:8
    at Array.map (<anonymous>)
    at C:\Users\Administrator\Desktop\liquidator-v3\node_modules\@blockworks-foundation\mango-client\src\utils\utils.ts:462:28
    at Generator.next (<anonymous>)
```
How do I resolve this issue?

**Comment by soapyp** [comment]
Hi @jmarrr this may be an issue related to your RPC provider. If it's persistent consider trying a different RPC.

**Comment by Mzsd** [comment]
I get the similar error + I get this error too
