### ISSUE TITLE
Keep getting Error reloading accounts: FetchError: request to rpc failed, reason: socket hang up, for all subsequent refreshAccounts method call

### ISSUE THREAD

**Issue by anishsamant** [blockworks-foundation/liquidator-v3#28]
The code successfully fetches the mango accounts in the initial `refreshAccounts` call, but for all subsequent calls it gives **Error reloading accounts: FetchError: request to rpc failed, reason: socket hang up.**

![Screenshot 2022-07-18 113744](https://user-images.githubusercontent.com/21247634/179759889-3b1e4850-b6d8-4ac7-9d68-8c5148729f52.png)

**Comment by soapyp** [comment]
Hi @anishsamant, this sounds like an issue with your RPC provider. Please check you are not being rate limited or similar

**Comment by samlaf** [comment]
Were you using the solana endpoint (https://api.devnet.solana.com) instead of mango endpoint (https://mango.rpcpool.com/946ef7337da3f5b8d3e4a34e7f88) by any chance @anishsamant ?

I'm observing similar behavior when using the solana public endpoint. First getting
```
Error: Error reloading accounts: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: socket hang up
    at /Users/samlaf/devel/solana/mangomarkets/liquidator-v3/scripts/mangoAccounts.ts:37:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/samlaf/devel/solana/mangomarkets/liquidator-v3/scripts/mangoAccounts.ts:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
and when I retry I get
```
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
Server responded with 429 Too Many Requests.  Retrying after 500ms delay...
......... (~ 100 times) ........... (and then)
/Users/samlaf/devel/solana/mangomarkets/liquidator-v3/scripts/mangoAccounts.ts:6
    try {
                                                                ^
Error: Error reloading accounts: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ECONNREFUSED 147.75.42.181:443
    at /Users/samlaf/devel/solana/mangomarkets/liquidator-v3/scripts/mangoAccounts.ts:37:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/samlaf/devel/solana/mangomarkets/liquidator-v3/scripts/mangoAccounts.ts:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
