### ISSUE TITLE
Consistent Transaction Errors

### ISSUE THREAD

**Issue by derekmi** [blockworks-foundation/liquidator-v3#7]
When running the liquidator, two errors consistently appear:
1. `Transaction failed: MangoErrorCode::InvalidParam`
2. `Transaction failed: MangoErrorCode::TriggerConditionFalse The trigger condition for this TriggerOrder is not met`

Any thoughts on how to resolve these errors?

Full logs follow:

```
Executing order for account H1bT2TXvQgVeUnS7bo1ZToov9oPqn7NmXFGsuf5JAf3Z
Started awaiting confirmation for 5oidV1QFLsCWLUsg1Qc8pzoYoYqsoaBYbR4XUz5atojSJaaK4Eg8P4RBYw2LsPNiJGYmB4GAtPVLhFC3c8LeNKSX size: 439
Thu, 02 Dec 2021 15:28:58 GMT  sending tx  5oidV1QFLsCWLUsg1Qc8pzoYoYqsoaBYbR4XUz5atojSJaaK4Eg8P4RBYw2LsPNiJGYmB4GAtPVLhFC3c8LeNKSX
Failed to execute trigger order for H1bT2TXvQgVeUnS7bo1ZToov9oPqn7NmXFGsuf5JAf3Z Error: Transaction failed: MangoErrorCode::InvalidParam; src/processor.rs:4524
    at MangoClient.<anonymous> (/home/ubuntu/liquidator-v3/node_modules/@blockworks-foundation/mango-client/src/client.ts:277:21)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/liquidator-v3/node_modules/@blockworks-foundation/mango-client/lib/src/client.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Refreshing accounts...
getAllMangoAccounts: 28.811s
Fetched 13138 accounts
Refreshing accounts...
Watching accounts...
getAllMangoAccounts: 31.274s
Fetched 13138 accounts
Executing order for account H1bT2TXvQgVeUnS7bo1ZToov9oPqn7NmXFGsuf5JAf3Z
Started awaiting confirmation for 5hjoztFDmZMeNXV9YCuSnYNLmBZj7AQQPkhbDoqeGgU4myGyee1aY5AzrHuWjuaCPXR2wAamZSZ5DovPumMyE3HK size: 439
Thu, 02 Dec 2021 15:33:19 GMT  sending tx  5hjoztFDmZMeNXV9YCuSnYNLmBZj7AQQPkhbDoqeGgU4myGyee1aY5AzrHuWjuaCPXR2wAamZSZ5DovPumMyE3HK
Thu, 02 Dec 2021 15:33:21 GMT  sending tx  5hjoztFDmZMeNXV9YCuSnYNLmBZj7AQQPkhbDoqeGgU4myGyee1aY5AzrHuWjuaCPXR2wAamZSZ5DovPumMyE3HK
Thu, 02 Dec 2021 15:33:23 GMT  sending tx  5hjoztFDmZMeNXV9YCuSnYNLmBZj7AQQPkhbDoqeGgU4myGyee1aY5AzrHuWjuaCPXR2wAamZSZ5DovPumMyE3HK
Thu, 02 Dec 2021 15:33:25 GMT  sending tx  5hjoztFDmZMeNXV9YCuSnYNLmBZj7AQQPkhbDoqeGgU4myGyee1aY5AzrHuWjuaCPXR2wAamZSZ5DovPumMyE3HK
Failed to execute trigger order for H1bT2TXvQgVeUnS7bo1ZToov9oPqn7NmXFGsuf5JAf3Z Error: Transaction failed: MangoErrorCode::TriggerConditionFalse The trigger condition for this TriggerOrder is not met; src/processor.rs:4550
    at MangoClient.<anonymous> (/home/ubuntu/liquidator-v3/node_modules/@blockworks-foundation/mango-client/src/client.ts:277:21)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/liquidator-v3/node_modules/@blockworks-foundation/mango-client/lib/src/client.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Executing order for account H1bT2TXvQgVeUnS7bo1ZToov9oPqn7NmXFGsuf5JAf3Z
Started awaiting confirmation for 38Cc1N6T3e2hUkAq69gcNQsCMkYSFCSbqQkHx14oAscNzKKnD2BjmCrS3FRFRHYXsYMbJEYhwRAHHhzbHmiPyWYr size: 439
Thu, 02 Dec 2021 15:33:58 GMT  sending tx  38Cc1N6T3e2hUkAq69gcNQsCMkYSFCSbqQkHx14oAscNzKKnD2BjmCrS3FRFRHYXsYMbJEYhwRAHHhzbHmiPyWYr
Thu, 02 Dec 2021 15:34:00 GMT  sending tx  38Cc1N6T3e2hUkAq69gcNQsCMkYSFCSbqQkHx14oAscNzKKnD2BjmCrS3FRFRHYXsYMbJEYhwRAHHhzbHmiPyWYr
Thu, 02 Dec 2021 15:34:02 GMT  sending tx  38Cc1N6T3e2hUkAq69gcNQsCMkYSFCSbqQkHx14oAscNzKKnD2BjmCrS3FRFRHYXsYMbJEYhwRAHHhzbHmiPyWYr
REST error for 38Cc1N6T3e2hUkAq69gcNQsCMkYSFCSbqQkHx14oAscNzKKnD2BjmCrS3FRFRHYXsYMbJEYhwRAHHhzbHmiPyWYr {
  slot: 109734384,
  confirmations: 0,
  status: { Err: { InstructionError: [Array] } },
  err: { InstructionError: [ 0, [Object] ] },
  confirmationStatus: 'processed'
}
Failed to execute trigger order for H1bT2TXvQgVeUnS7bo1ZToov9oPqn7NmXFGsuf5JAf3Z Error: Transaction failed: MangoErrorCode::InvalidParam; src/processor.rs:4524
    at MangoClient.<anonymous> (/home/ubuntu/liquidator-v3/node_modules/@blockworks-foundation/mango-client/src/client.ts:277:21)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/liquidator-v3/node_modules/@blockworks-foundation/mango-client/lib/src/client.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dafyddd** [comment]
Those errors just mean you weren't first in executing others' stop loss orders. You get paid 100x the tx fee when you succeed so overall you're probably net positive.

**Comment by derekmi** [comment]
Got it, thanks @dafyddd!
